[package]
name = "stoffelnet"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
quinn = "0.11.8"
rustls = "0.23.29"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.46.1", features = ["full"] }
uuid = { version = "1.17.0", features = ["v4"] }
rcgen = "0.14.2"
ark-ff = "0.5.0"
thiserror = "2.0.12"
async-trait = "0.1.88"
bincode = "1.3.3"
tracing = "0.1.41"
dashmap = "7.0.0-rc2"
